<?php

namespace App\UseCase\Visit\Create;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\IntegerType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class Form extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('employeeId', IntegerType::class)
            ->add('serviceId', IntegerType::class)
            ->add('date', TextType::class)
            ->add('time', TextType::class);
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Command::class,
            'csrf_token_id' => 'csrf_token'
        ]);
    }

    public function getBlockPrefix(): string
    {
        return ''; // TODO: Change the autogenerated stub
    }

}